# read config setted in argparse_wrapper.py 
OUTDIR = config["outdir"]
TARGET = config["fasta"]
FR = config["fr"]
RR = config["rr"]
K = config["k"]
HDIST = config["hdist"]
EXECUTION_FOLDER = config['execution_folder']
MODE = config["mode"]
PREFIX = config["prefix"]

## provide here final pipeline outputs, without intermediates 
rule all:
    input:
        target_assembly = f"{OUTDIR}/assembly/{PREFIX}_target.fasta",

## list here all environments
rule envs:
    input:
        minimap2 = "../envs/minimap2.yaml",
        spades = "../envs/spades.yaml",
        bbduk = "../envs/bbduk.yaml",

envs = rules.envs.input 

if MODE == "minimap2":
    include: "./rules/minimap2.smk"
    TARGET_FR = rules.extract_properly_paired_reads.output.target_fr
    TARGET_RR = rules.extract_properly_paired_reads.output.target_rr
elif MODE == "bbduk":
    include: "./rules/bbduk.smk"
    TARGET_FR = rules.bbduk.output.target_fr
    TARGET_RR = rules.bbduk.output.target_rr

include: "./rules/spades.smk"
